import { useRef, useState } from 'react'
import copy from '../Images/copy.svg';

const API = ({ setApi, api }) => {
    const modalRef = useRef()
    const [copied, setCopied] = useState(false);
    const [generated, setGenerated] = useState(false)
    const textToCopy = 'hsjuygyd774gwducjuo9892e7t28nxgjgct20kycpai27bjxj6Xtrcf5reftgurduftdff'

    const handleClose = (e) => {
        if (modalRef.current === e.target) {
            setApi(false)
            setGenerated(false)
        }
    }

    const handleCopy = () => {
        navigator.clipboard.writeText(textToCopy)
        setCopied(true)

        setTimeout(() => setCopied(false), 1250);
    }

    return (
        <>
            {api && (
                <div>
                    {!generated ? (
                        <div onClick={handleClose} ref={modalRef} className='fixed inset-0 z-50 flex lg:ml-[222.2px] items-center justify-center bg-opacity-20 bg-black'>
                            <div className='bg-white md:w-[762px] sd:w-[500px] rounded-lg sm:py-[60px] py-10 sm:px-[41px] px-[30px] sm:mx-0 mx-5 flex flex-col sm:gap-10 gap-6'>
                                <p className='text-[#252525] text-[24px] font-[450]'>Integration/API Key</p>
                                <div className='bg-[#F6F6F6] text-[#25252580] flex flex-col gap-5 text-[16px] font-normal rounded-lg py-6 px-9'>
                                    <p>Your Secret API Keys can be Generated below. Please note that we do not display your API keys again after they’ve been generated by you.</p>
                                    <p>Do not share your API Keys with others, or expose it in other browser or other client-side code. In order to protect the security of your Account. </p>
                                </div>
                                <button onClick={() => setGenerated(true)} className='py-[10px] px-10 border bg-[#441890] hover:bg-[#441890CC] w-full text-white border-[#441890] rounded-md'>Generate API Key</button>

                            </div>
                        </div>
                    ) : (
                        <div onClick={handleClose} ref={modalRef} className='fixed inset-0 z-50 flex lg:ml-[222.2px] items-center justify-center bg-opacity-20 bg-black'>
                            <div className='bg-white relative md:w-[762px] sd:w-[500px] rounded-lg sm:py-[60px] py-10 sm:px-[41px] px-[30px] sm:mx-0 mx-5 flex flex-col sm:gap-10 gap-6'>
                                {copied && (
                                    <p className='py-2 px-4 rounded-md absolute top-2 bg-[#441890] text-white left-1/2 -translate-x-1/2'>Copied</p>
                                )}
                                <div>
                                    <p className='text-[#252525] text-[24px] font-[450]'>Your API Key has been generated</p>
                                    <p className='text-[#25252580] text-[16px] font-normal'>Click the copy button below to copy your generated API key</p>
                                </div>
                                <div className='bg-[#F6F6F6] text-[#25252580] flex flex-col gap-5 text-[16px] font-normal rounded-lg py-6 px-9'>
                                    <p>Please be sure to save API key generated below. For security reasons, you wont be able to view it again through your mhapy account. If you lose this API key, you will need to generate a new one. </p>
                                </div>
                                <div className='flex items-center gap-[14px]'>
                                    <input
                                        readOnly
                                        type="text"
                                        name=""
                                        id=""
                                        value={'hsjuygyd774gwducjuo9892e7t28nxgjgct20kycpai27bjxj6Xtrcf5reftgurduftdff'}
                                        className='sm:py-[10px] py-[4px] outline-none text-[19px] font-normal w-full px-[25px] border border-[#25252533] rounded-lg'
                                    />
                                    <img onClick={handleCopy} className='sm:size-[50px] w-[38px] cursor-pointer' src={copy} alt="" />
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            )}
        </>
    )
}

export default API